foodies/urls.py
from django.urls import path
from foodies import views

app_name = 'foodies'

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('category/<slug:category_name_slug>/', views.show_category, name='show_category'), #/categories/african
    path('add-category/', views.add_category, name='add_category'),
    path('register/', views.register, name='register'),  # New mapping!
    path('login/', views.user_login, name='login'), # /login
    path('restricted/', views.restricted, name='restricted'),
    path('logout/', views.user_logout, name='logout'),
    path('user-profile/', views.user_profile, name = 'user_profile'), #/user-profile
    path('user-profile/update/', views.user_profile_update, name = 'user_profile_update'), #/user-profile
    path('user-profile/meals/add/', views.add_meal, name='add_meal'),  # /add_meal
    path('user-profile/meals/<int:meal_id>/edit/', views.edit_meal, name='edit_meal'),  # /add_meal
    path('user-profile/meals/<int:meal_id>/delete/', views.delete_meal, name='delete_meal'),
    path('user-profile/meals/', views.user_meals, name='user_meals'),  #/user-profile/meals
    path('user-profile/requests/<int:request_id>/delete/', views.delete_request, name='delete_request'),  #/user-profile/requests
    path('user-profile/requests/', views.user_requests, name='user_requests'),  #/user-profile/requests
    path('user-profile/reviews/', views.user_reviews, name='user_reviews'),  #/user-profile/reviews
    path('register-diners/', views.register_diners, name ='register_diners'), #/register-diners
    path('user-profile/allergies/', views.show_allergies, name='show_allergies'),  #/user-profile/reviews
    path('user-profile/allergies/add', views.add_allergy, name='add_allergy'),  #/user-profile/reviews
    path('user-profile/allergies/<int:allergy_id>/edit', views.edit_allergy, name='edit_allergy'),  #/user-profile/reviews
    path('user-profile/allergies/<int:allergy_id>/delete', views.delete_allergy, name='delete_allergy'),  #/user-profile/reviews
    path('register-diners/', views.register_diners, name = 'register_diners'), #/register-diners
    path('register-cookers/', views.register_cookers, name = 'register_cookers'), #/register-cookers
    path('search/', views.search, name='search'),  #/search
    path('search-cookers/', views.search_cookers, name='search_cookers'),  #/search
    path('contact-us/', views.contact_us, name = 'contact_us'), #/contact-us
    path('contact_reply/', views.contact_reply, name='contact_reply'),
    path('meal/<int:meal_id>/', views.show_meal_details, name='meal_details'),
    path('meal/<int:meal_id>/request/', views.request_meal, name='request_meal'),  # /request a meal
    path('public-user-profile/<int:id>/', views.public_user_profile, name='public_user_profile'),  # /public profile url
    path('is_user_login/', views.is_user_login, name='is_user_login'),
    path('user-profile/add-review-diner/<int:request_id>', views.add_review_to_diner, name='add_review_to_diner'),  #/add_review/
    path('user-profile/add-review-cooker/<int:request_id>', views.add_review_to_cooker, name='add_review_to_cooker'),  #/add_review/
]

foodies_project/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from foodies import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('foodies.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

foodies/forms.py
from django import forms
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit
from betterforms.multiform import MultiModelForm
from foodies.models import Meal, Category, UserProfile, Ingredient, Request, Allergy, Review
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError

class CategoryForm(forms.ModelForm):
    name = forms.CharField(max_length=Category.NAME_MAX_LENGTH,
                           help_text="Please enter the category name.")
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    likes = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    slug = forms.CharField(widget=forms.HiddenInput(), required=False)

    # An inline class to provide additional information on the form.
    class Meta:
    # Provide an association between the ModelForm and a model
        model = Category
        fields = ('name',)

class MealForm(forms.ModelForm):
    title = forms.CharField(max_length=Meal.TITLE_MAX_LENGTH, help_text="Please enter the title of the meal.", label="Meal Name")
    price = forms.FloatField(help_text="Please enter the price for this meal")
    category = forms.ModelChoiceField(queryset=Category.objects.all().order_by('name'), help_text="Please select the category for this meal")

    class Meta:
        model = Meal
        fields = ('title', 'picture', 'price', 'category', 'ingredients', 'recipe')

class IngredientsForm(forms.ModelForm):
    name = forms.CharField(required=True, help_text="Please enter one ingredient", label="Ingredient Name")
    vegetable = forms.CharField(required=False, help_text="Please enter the vegetables")
    typeofmeat = forms.CharField(required=False, help_text="Please enter the type of meat", label="Type of Meat")
    meal = MealForm

    class Meta:
        model = Ingredient
        fields = ('name', 'vegetable', 'typeofmeat',)

# This form takes the IngredientsForm and the MealForm at the same time for being handled in views
class mealIngredientMultiForm(MultiModelForm):
    form_classes = {
        'meal': MealForm,
        'ingredients': IngredientsForm,
    }

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    def clean(self):
       email = self.cleaned_data.get('email')
       if User.objects.filter(email=email).exists():
            raise ValidationError("This email already exists")
       return self.cleaned_data

    def __init__(self, *args, **kwargs):
        super(UserForm, self).__init__(*args, **kwargs)
        self.fields['email'].required = True

    class Meta:
        model = User
        fields = ('username', 'email','password',)

class UserProfileForm(forms.ModelForm):
    isCooker = forms.BooleanField(initial=False, required=False, label='Are you a cooker?')
    isDinner = forms.BooleanField(initial=False, required=False, label='Are you a dinner?')

    def __init__(self, *args, **kwargs):
        super(UserProfileForm, self).__init__(*args, **kwargs)
        self.fields['name'].required = True

    class Meta:
        model = UserProfile
        fields = ('name', 'isCooker', 'isDinner')

class UserUpdateForm(forms.ModelForm):
    password = None

    def __init__(self, *args, **kwargs):
        super(UserUpdateForm, self).__init__(*args, **kwargs)
        self.fields['email'].required = True

    class Meta:
        model = User
        exclude = ['username', 'password']
        fields = ('email',)


class UserProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('name', 'picture', 'address', 'city', 'specialty', 'phone', 'personalDescription', 'isCooker', 'isDinner',)

class RequestAMealForm(forms.ModelForm):

    message = forms.CharField(widget=forms.Textarea, help_text="Write any specifications and the number of orders you want")

    class Meta:
        model = Request
        fields = ('content', 'message',)

class AllergiesForm(forms.ModelForm):
    class Meta:
        model = Allergy
        fields = ('name',)


class ReviewsForm(forms.ModelForm):
    rating = forms.IntegerField(required=True, help_text="Rate the cooker", label="Rating")
    content = forms.CharField(required=True, help_text="Rating description", label="Description")

    class Meta:
        model = Review
        fields = ('title', 'rating','content',)

foodies/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from foodies.models import Category, Meal, User, UserProfile, Request, Ingredient, Allergy, Review
from django.urls import reverse
from foodies.forms import CategoryForm, MealForm, UserForm, UserProfileForm, IngredientsForm, UserUpdateForm, UserProfileUpdateForm, RequestAMealForm, AllergiesForm, ReviewsForm
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.decorators import login_required
from datetime import datetime
from django.contrib.auth import get_user_model
from django.contrib import messages
from foodies.bing_search import run_query
from django.db.models import Q


def index(request):
    user_list=UserProfile.objects.order_by('-id')[:6]
    category_list = Category.objects.order_by('-likes')[:6]
    meal_list = Meal.objects.order_by('-views')[:6]
    context_dict = {        
        'categories': category_list,
        'meals': meal_list,  
        'user_info':user_list 
    }
    visitor_cookie_handler(request)
    return render(request, 'foodies/index.html', context=context_dict)



def about(request):
    context_dict = {}
    visitor_cookie_handler(request)
    context_dict['visits'] = request.session['visits']
    return render(request, 'foodies/about.html', context=context_dict)


def show_category(request, category_name_slug):
    context_dict = {}

    try:
        category = Category.objects.get(slug=category_name_slug)

        meals = Meal.objects.filter(category=category)

        context_dict['meals'] = meals

        context_dict['category'] = category
    except Category.DoesNotExist:
        context_dict['category'] = None
        context_dict['meals'] = None

    return render(request, 'foodies/category.html', context=context_dict)


@login_required
def add_category(request):
    form = CategoryForm()

    if request.method == 'POST':
        form = CategoryForm(request.POST)

        if form.is_valid():
            form.save(commit=True)

            return redirect('foodies/index')
        else:
            print(form.errors)

    return render(request, 'foodies/add_category.html', {'form': form})


@login_required
def add_meal(request):
    profile_title = "Add a Meal"

    try:
        user = User.objects.get(username=request.user.username)
    except User.DoesNotExist:
        return None

    userProfile = UserProfile.objects.filter(user=user).first()
    user_info = {
        'id': userProfile.id,
        'email': user.email,
        'isCooker': userProfile.isCooker,
        'isDinner': userProfile.isDinner
    }

    if user_info.get('isCooker') is False:
        return HttpResponseRedirect(reverse('foodies:user_profile'))

    if request.method == 'POST':
        meal_form = MealForm(request.POST, request.FILES)

        if meal_form.is_valid():

            meal = meal_form.save(commit=False)
            user_profile = UserProfile.objects.filter(user=request.user).first()
            meal.user = user_profile

            if 'picture' in request.FILES:
                meal.picture = request.FILES['picture']

            meal.save()

            return redirect('foodies:user_meals')
        else:
            messages.error(request, meal_form.errors)
            return HttpResponseRedirect(reverse('foodies:add_meal'))
    else:
        meal_form = MealForm()

    return render(request, 'foodies/add_meal.html',
                  {'meal_form': meal_form, 'profile_title': profile_title, 'user_info': user_info})


@login_required
def edit_meal(request, meal_id):
    try:
        user = User.objects.get(username=request.user.username)
    except User.DoesNotExist:
        return None

    userProfile = UserProfile.objects.filter(user=user).first()
    user_info = {
        'id': userProfile.id,
        'email': user.email,
        'isCooker': userProfile.isCooker,
        'isDinner': userProfile.isDinner
    }

    if user_info.get('isCooker') is False:
        return HttpResponseRedirect(reverse('foodies:user_profile'))

    try:
        meal = Meal.objects.get(id=meal_id)
    except User.DoesNotExist:
        messages.error(request, 'The meal does not exists')
        return HttpResponseRedirect(reverse('foodies:edit_meal', kwargs={'meal_id': meal_id}))

    meal_form = MealForm(request.POST or None, instance=meal)

    if request.method == 'POST':
        if meal_form.is_valid():

            meal_form.save()
            meal = meal_form.save(commit=False)

            if 'picture' in request.FILES:
                meal.picture = request.FILES['picture']

            meal.save()
            return HttpResponseRedirect(reverse('foodies:user_meals'))

        else:
            print(meal_form.errors)
            messages.error(request, meal_form.errors)
            return HttpResponseRedirect(reverse('foodies:edit_meal', kwargs={'meal_id': meal_id}))

    return render(request, 'foodies/edit_meal.html',
                  {'meal_form': meal_form, 'meal_id': meal_id, 'user_info': user_info})


def delete_meal(request, meal_id):
    try:
        meal = Meal.objects.get(id=meal_id)
    except Request.DoesNotExist:
        return redirect('foodies:user_meals')

    meal.delete()
    return redirect('foodies:user_meals')


def register(request):
    # A boolean value for telling the template
    # whether the registration was successful.
    # Set to False initially. Code changes value to
    # True when registration succeeds.
    registered = False

    # If it's a HTTP POST, we're interested in processing form data.
    if request.method == 'POST':
        # Attempt to grab information from the raw form information.
        # Note that we make use of both UserForm and UserProfileForm.
        user_form = UserForm(request.POST)
        profile_form = UserProfileForm(request.POST)

        # If the two forms are valid...
        if user_form.is_valid() and profile_form.is_valid():
            # Save the user's form data to the database.
            data = request.POST.copy()
            if data.get('isCooker') == None and data.get('isDinner') == None:
                messages.error(request, 'Invalid: Check at least 1 checkbox for Cooker or Dinner or both.')
                return HttpResponseRedirect('/register')

            user = user_form.save()

            # Now we hash the password with the set_password method.
            # Once hashed, we can update the user object.
            user.set_password(user.password)
            user.save()

            # Now sort out the UserProfile instance.
            # Since we need to set the user attribute ourselves,
            # we set commit=False. This delays saving the model
            # until we're ready to avoid integrity problems.
            profile = profile_form.save(commit=False)
            profile.user = user
            profile.name = data.get('name')

            if data.get('isCooker') is not None:
                profile.isCooker = True

            if data.get('isDiner') is not None:
                profile.isDinner = True

            # Did the user provide a profile picture?
            # If so, we need to get it from the input form and
            # put it in the UserProfile model.
            if 'picture' in request.FILES:
                profile.picture = request.FILES['picture']

            # Now we save the UserProfile model instance.
            profile.save()

            # Update our variable to indicate that the template
            # registration was successful.
            registered = True
            login(request, user)
            return redirect('foodies:index')
        else:
            # Invalid form or forms - mistakes or something else?
            # Print problems to the terminal.
            print(user_form.errors, profile_form.errors)
    else:
        # Not a HTTP POST, so we render our form using two ModelForm instances.
        # These forms will be blank, ready for user input.
        user_form = UserForm()
        profile_form = UserProfileForm()

    # Render the template depending on the context.
    return render(request, 'foodies/register.html',
                  context={'user_form': user_form, 'profile_form': profile_form, 'registered': registered})


def user_login(request):
    if request.method == 'POST':

        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request, user)
                return redirect(reverse('foodies:index'))
            else:
                return HttpResponse("Your Foodies account is disabled.")
        else:
            print(f"Invalid login details: {username}, {password}")
            messages.error(request, 'Invalid login details.')
            return redirect(reverse('foodies:login'))

    else:
        return render(request, 'foodies/login.html')


@login_required
def restricted(request):
    return render(request, 'foodies/restricted.html')


# Use the login_required() decorator to ensure only those logged in can
# access the view.
@login_required
def user_logout(request):
    # Since we know the user is logged in, we can now just log them out.
    logout(request)
    # Take the user back to the homepage.
    return redirect(reverse('foodies:index'))


def get_server_side_cookie(request, cookie, default_val=None):
    val = request.session.get(cookie)
    if not val:
        val = default_val
    return val


def visitor_cookie_handler(request):
    visits = int(get_server_side_cookie(request, 'visits', '1'))
    last_visit_cookie = get_server_side_cookie(request, 'last_visit', str(datetime.now()))
    last_visit_time = datetime.strptime(last_visit_cookie[:-7], '%Y-%m-%d %H:%M:%S')

    if (datetime.now() - last_visit_time).days > 0:

templates/foodies/add_review.html
{% extends 'foodies/user_profile_base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block title_block %}
   Add review
{% endblock %}

{% block profile_block %}

<div class="container"> 
	<div class="col-sm-10 offset-sm-1">
		<div>
			{% for message in messages %}
			<div class="alert alert-danger">
				<a class="close" href="#" data-dismiss="alert">×</a>
				{{ message }}
			</div>
			{% endfor %}
		</div>
		<form id="add_meal_form" method="post" action="{% url action_url request_id %}" enctype="multipart/form-data">
			{% csrf_token %}
			{{ review_form | crispy }}
			<a class="btn btn-danger" href="{% url 'foodies:user_requests' %}">Cancel</a>
			<input class="btn btn-primary" type="submit" name="submit" value="Add Review" />
		</form>
	</div>
</div>

{% endblock %}

templates/foodies/contact_us.html
{% extends 'foodies/base.html' %}

{% load static %}

{% block title_block %}
    Contact Us
{% endblock %}

{% block body_block %}



	<div class="row justify-content-center">
		<div class="col-sm-12 mb-4">			
            <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2238.4437388948595!2d-4.290697683790093!3d55.87231698058555!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0x0!2zNTXCsDUyJzIwLjMiTiA0wrAxNycxOC42Ilc!5e0!3m2!1sen!2suk!4v1584885669909!5m2!1sen!2suk" width="100%" height="307" frameborder="0" style="border:0;" allowfullscreen="" aria-hidden="false" tabindex="0"></iframe>
        </div>
        
    </div>
    <div class="container"> 
        <div class="row justify-content-center">
            <div class="col-sm-6">
                <ul class="list-unstyled">
                    <li class="mb-2"><h2>Contact Info</h2></li>
                    <li class="mb-2"><strong>Address:</strong> 123 University Av. Glasgow</li>
                    <li class="mb-2"><strong>Phone:</strong> <a href="tel:7923782100">79 23 78 21 00</a></li>
                    <li class="mb-2"><strong>Email:</strong> <a href="mailto:hello@foodies.com">hello@foodies.com</a></li>
                </ul>
            </div>
            <div class="col-sm-6 ">			
                <div class="card border-dark rounded-0">
                    <div class="card-header p-0">
                        <div class="bg-info text-white text-center py-2">
                            <h3><i class="fa fa-envelope"></i> Contact Foodies</h3>
                        </div>
                    </div>
                    <div class="card-body p-3">
                        <form target="_blank" action="{% url 'foodies:contact_reply' %}" method="POST">
                            {% csrf_token %} 
                            <!--Body-->
                            <div class="form-group">
                                <div class="input-group mb-2">
                                    <div class="input-group-prepend">
                                        <div class="input-group-text"><i class="fas fa-user"></i></div>
                                    </div>
                                    <input type="text" class="form-control" id="username" name="username" placeholder="Username" required>
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="input-group mb-2">
                                    <div class="input-group-prepend">
                                        <div class="input-group-text"><i class="fas fa-envelope"></i></div>
                                    </div>
                                    <input type="email" class="form-control" id="email" name="email" placeholder="youremail@123.com" required>
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="input-group mb-2">
                                    <div class="input-group-prepend">
                                        <div class="input-group-text"><i class="fas fa-comment"></i></div>
                                    </div>
                                    <textarea class="form-control" placeholder="Type Your Message" required></textarea>
                                </div>
                            </div>
                            <div class="text-center">
                                <input class="btn btn-danger" type="submit" value="Submit request" />
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>  
	</div>


{% endblock %}

templates/foodies/edit_allergy.html
{% extends 'foodies/user_profile_base.html' %}
{% load staticfiles %}

{% load crispy_forms_tags %}

{% block title_block %}
    Add a Meal
{% endblock %}

{% block profile_block %}
<div class="container"> 
    <div class="col-sm-10 offset-sm-1">
        <div>
            {% for message in messages %}
            <div class="alert alert-danger">
                <a class="close" href="#" data-dismiss="alert">×</a>
                {{ message }}
            </div>
            {% endfor %}
        </div>
        <form id="add_meal_form" method="post" action="{% url 'foodies:edit_allergy' allergy_id %}">
            {% csrf_token %}
            {{ allergies_form | crispy }}
            <a class="btn btn-danger" href="{% url 'foodies:user_meals' %}">Cancel</a>
            <input class="btn btn-primary" type="submit" name="submit" value="Add Allergy" />
        </form>
    </div>
</div>
{% endblock %}

templates/foodies/search.html
{% extends 'foodies/base.html' %}
{% load staticfiles %}

{% block title_block %}
    Search
{% endblock %}

{% block body_block %}

<div class="container">
	<h1>Search with Foodies</h1>

	<div class="row">
		<div class="col-sm-6 offset-sm-3">
			<form class="form-inline w-100" id="user-form" method="get" action="{% url 'foodies:search' %}">
				{% csrf_token %}
				<div class="form-group">
					<input class="form-control" type="text" size="50" name="query" id="query" value="{{ query }}" />
				</div>
				<button class="btn btn-primary" type="submit" name="submit">Search</button>
			</form>
		</div>
		{% if results_meals|length > 0 %}
		<div class="col-sm-12 mt-5">
			<div class="row">
				<div class="col-sm-12 mb-4">
					<h2 class="text-center text-danger">Meals</h2>
				</div>
				{% for meal in results_meals %}
				<div class="col-sm-4 mb-4">
					<a class="d-block text-decoration-none" href="/meal/{{ meal.id }}">
						<div class="viewed_meals" style="background-image:url({{ MEDIA_URL }}{{ meal.picture }});"></div>
						<p class="text-center">{{ meal.title }}</p>
					</a>
				</div>
				{% endfor %}
			</div>
		</div>
		{% endif %}

		{% if results_cats|length > 0 %}
		<div class="col-sm-12 mt-5">
			<div id="categories" class="row">
				<div class="col-sm-12 mb-4">
					<h2 class="text-center text-danger">Categories</h2>
				</div>
				{% for cat in results_cats %}
				<div class="col-sm-3">
					<div class="position-relative random-color">
						<div class="position-absolute w-100 h-100 bg"></div>
						<a class="m-0 position-relative h4 d-block text-white text-center text-decoration-none" href="{% url 'foodies:show_category' cat.slug %}">{{ cat.name }}</a>
					</div>
				</div>
				{% endfor %}
			</div>
		</div>
		{% endif %}
		
		{% if results_cookers|length > 0 %}
		<div class="col-sm-12 mt-5">
			<div id="best-cookers" class="row">
				<div class="col-sm-12 mb-4">
					<h2 class="text-center text-danger">Cookers</h2>
				</div>
				{% for cooker in results_cookers %}
				<div class="col-sm-4">
					<div class="text-center">
						<div class="mx-auto picture background-image cover round" style="background-image:url({{ MEDIA_URL }}{{ cooker.picture }}); width: 200px; height: 200px;"></div>
						<a href="/public-user-profile/{{ cooker.id }}">{{ cooker.name }}</a>	
					</div>
				</div>
				{% endfor %}
			</div>
		</div>
		{% endif %}

		{% if results_cookers|length > 0 and results_cats|length > 0 and results_meals|length > 0 %}
		<div class="col-sm-12">
			<h3 class="mt-3 text-center">Nothing found for the search <strong>{{ query }}</strong></h3>
		</div>
		{% endif %}
	</div>


</div>	

{% endblock %}

templates/foodies/user_allergies.html
{% extends 'foodies/user_profile_base.html' %} 
{% load static %} 

{%block title_block %} 
User Meals 
{% endblock %} 

{% block profile_block %}

	<div class="card">
		<div class="card-header" id="headingOne">
			<button class="btn btn-primary mb-0">
				<i class="fas fa-utensils"> <a href="{% url 'foodies:add_allergy' %}"> Add Allergy</a></i>
			</button>
		</div>
	</div>
	
	<div class="user_meals_list">
		<ul class="list-group">
            {% for allergy in allergies %}
			<li class="list-group-item">
				<div class="row w-100 d-flex align-items-center">
					<div class="col-sm-9">
						<h3 class="mb-1">{{ allergy.name }}</h3>
					</div>
					<div class="col-sm-3">
						<a class="btn btn-success" href="{% url 'foodies:edit_allergy' allergy.id %}">Edit</a>
						<a class="btn btn-danger" href="{% url 'foodies:delete_allergy' allergy.id %}">Detele</a>
					</div>
				</div>
			</li>
            {% endfor %}
		</ul>
	</div>
	
</div>

{% endblock %}

templates/foodies/user_profile_base.html
{% extends 'foodies/base.html' %}
{% load staticfiles %}

{% block title_block %}
    User Profile
{% endblock %}

{% block body_block %}
<h1 class="text-center">{{ profile_title }}</h1>

<section class="container">
    <section class="row mt-3">
        <div class="col-sm-3">
            <a class="list-group-item list-group-item-action {% if request.path == '/user-profile/' or request.path == '/user-profile/update/' %} active {% endif %}" href="{% url 'foodies:user_profile' %}" aria-controls="home">User Profile</a>
            {% if user_info.isCooker == 1 %}
            <a class="list-group-item list-group-item-action {% if request.path == '/user-profile/meals/' %} active {% endif %}" href="{% url 'foodies:user_meals' %}" aria-controls="profile">Meals</a>
            {% endif %}
            <a class="list-group-item list-group-item-action {% if request.path == '/user-profile/requests/' %} active {% endif %}" href="{% url 'foodies:user_requests' %}" aria-controls="requests">Requests</a>
            <a class="list-group-item list-group-item-action {% if request.path == '/user-profile/reviews/' %} active {% endif %}" href="{% url 'foodies:user_reviews' %}" aria-controls="requests">Reviews</a>
            {% if user_info.isDinner == 1 %}
            <a class="list-group-item list-group-item-action {% if request.path == '/user-profile/allergies/' %} active {% endif %}" href="{% url 'foodies:show_allergies' %}" aria-controls="allergies">Allergies</a>
            {% endif %}
        </div>
        <div class="col-sm-9">
            {% block profile_block %}
            {% endblock %}
        </div>
    </section>
</section>
{% endblock %}
        

templates/foodies/user_requests.html
{% extends 'foodies/user_profile_base.html' %}
{% load static %}
{% load foodies_template_tags %}

{% block title_block %} 
    User Meals 
{% endblock %} 

{% block profile_block %}

<div class="accordion" id="accordionExample">
    {% if requests_as_cooker|length > 0 %}
    <div>
        <h3 class="text-center">Requests as cooker</h3>
        <ul class="list-group">
            {% for row in requests_as_cooker %}
            <li class="list-group-item">
                <div class="row w-100 d-flex align-items-center">
                    <div class="col-sm-8">
                        <h3 class="mb-1"><strong>Client: </strong>{{ row.name }}</h3>
                        <p class="mb-1"><strong>email: </strong>{{ row.email }}</p>
                        <p class="mb-1"><strong>Content: </strong>{{ row.content }}</p>
                        <p class="mb-1"><strong>Message: </strong>{{ row.message }}</p>
                        <p class="mb-1"><strong>Date of order: </strong>{{ row.date }}</p>
                    </div>
                    <div class="col-sm-4">
                        <a class="btn btn-primary" href="{% url 'foodies:add_review_to_diner' row.id %}">Write Review</a>
                        <a class="btn btn-danger" href="{% url 'foodies:delete_request' row.id %}">Delete</a>
                    </div>
                </div>
            </li>
            {% endfor %}
        </ul>
    </div>
    {% endif %}
    {% if requests_as_diner|length > 0 %}
    <div>
        <h3 class="text-center">Requests as diner</h3>
        <ul class="list-group">
            {% for row in requests_as_diner %}
            <li class="list-group-item">
                <div class="row w-100 d-flex align-items-center">
                    <div class="col-sm-8">
                        <h3 class="mb-1"><strong>Client: </strong>{{ row.name }}</h3>
                        <p class="mb-1"><strong>email: </strong>{{ row.email }}</p>
                        <p class="mb-1"><strong>Content: </strong>{{ row.content }}</p>
                        <p class="mb-1"><strong>Message: </strong>{{ row.message }}</p>
                        <p class="mb-1"><strong>Date of order: </strong>{{ row.date }}</p>
                    </div>
                    <div class="col-sm-4">
                        <a class="btn btn-primary" href="{% url 'foodies:add_review_to_cooker' row.id %}">Write Review</a>
                        <a class="btn btn-danger" href="{% url 'foodies:delete_request' row.id %}">Delete</a>
                    </div>
                </div>
            </li>
            {% endfor %}
        </ul>
    </div>
    {% endif %}
</div>

{% endblock %}